[general]
# https://terminalcolors.com/alacritty/
import = ["~/.config/alacritty/themes/ayu-dark.toml"]

[window]
padding.x = 10
padding.y = 10
startup_mode = "Maximized"

decorations = "None"

opacity = 0.8
blur = true

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "M"
mods = "Control|Shift"
action = "ToggleMaximized"
