[general]
# https://terminalcolors.com/alacritty/
import = ["~/.config/alacritty/themes/ayu-dark.toml"]

[window]
startup_mode = "Maximized"

decorations = "Full"

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "M"
mods = "Control|Shift"
action = "ToggleMaximized"
